channels:
  - conda-forge
  - defaults
dependencies:
  - gdal>=3.1
  - rasterio>=1.2.0
  - geopandas>=0.9.0
  - xarray>=0.17.0
  - jupyterlab>=3.0.0
  - pip
  - dask-labextension
  - pip:
        - stackstac