channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8.0
  - gdal>=3.1
  - rasterio>=1.2.0
  - geopandas>=0.9.0
  - xarray>=0.17.0
  - nodejs>=12.0.0
  - dask-labextension
  - nbgitpuller>-0.9.0
  - pip:
        - stackstac
        - sat-search